name: cypress

on:
  push:
    branches:
      - main

jobs:
  cypress_tests:
    - uses: cypress-io/github-action@v5
      with:
        command: npm run test:e2e
        start: npm run start-prod
        wait-on: http://localhost:5000