name: Health Check

on:
  schedule:
    - cron: "0 0 15 * *"

jobs:
  onko_terveys_kunnossa:
    runs-on: ubuntu-20.04
    steps:
      - name: Check health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-1o5p.onrender.com/health
