name: Periodic Health Check

on:
  push:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if website is up
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-ljkm.onrender.com'
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true
          retry-all: true
