name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Test de saltear
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: |
          if echo "$COMMIT_MESSAGES" | grep -q "#skip"; then
            echo "Skipping step"
          else
            echo "Executing step"
          fi
      - name: Test de saltear V2
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: echo "$COMMIT_MESSAGES" | grep -q "#skip"
        run: echo "S"
      - name: Test de saltear V3
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        if: {{ COMMIT_MESSAGES | grep -q "#skip" }}
        run: echo "S"